# -*- coding: utf-8 -*-
"""bot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8kuCkMrgoOVBiI81hgsSj9A5h0Gwyps
"""

<<<<<<< HEAD
import os
import time
=======

>>>>>>> 342120564ac98a4662f027f9c4e3ab6511a3559c
import tweepy

# Load keys from environment variables
BEARER_TOKEN = os.getenv("BEARER_TOKEN")
API_KEY = os.getenv("API_KEY")
API_SECRET = os.getenv("API_SECRET")
ACCESS_TOKEN = os.getenv("ACCESS_TOKEN")
ACCESS_SECRET = os.getenv("ACCESS_SECRET")

<<<<<<< HEAD
def main():
    # Init client
    client = tweepy.Client(
        bearer_token=BEARER_TOKEN,
        consumer_key=API_KEY,
        consumer_secret=API_SECRET,
        access_token=ACCESS_TOKEN,
        access_token_secret=ACCESS_SECRET
    )

    # Test tweet (only once at startup)
    try:
        client.create_tweet(text="Bot started 🚀")
        print("Tweet sent successfully!")
    except Exception as e:
        print("Error sending startup tweet:", e)

    # Keep the bot alive forever
    while True:
        print("Bot running...")   # shows in Railway logs
        time.sleep(30)            # wait 30 seconds

if __name__ == "__main__":
    main()
=======
client.create_tweet(text="Test")
print("Tweet sent successfully!")
>>>>>>> 342120564ac98a4662f027f9c4e3ab6511a3559c
